### ISSUE TITLE
Gather game assets (sound/images)

### ISSUE THREAD

**Issue by jesus-perez-dev** [jesus-perez-dev/Software-Engineering-Project-COMP-CO867#9]
-Sound BucketDropSuccess
-Sound BucketDropFail
-Sound SensorActivate
-Texture BucketTexture
-Texture MarbleTexture
-Texture TrapDoorTexture
-Texture SensorTexture

**Comment by SKIMSTER0** [comment]
Omitted Assets:
- TrapDoorTexture 
Will be a simple rectangle on conveyer rectangle that may rotate, or switch between closed/open state if stretch goal not reached)

Extra Assets:
- conveyerSound
- sensorSignalOn
- sensorSignalOff

All sound assets are from zapsplat.com. The use a 'standard license' which means crediting is neccessary. Add a text in the project description/main menu or a credits screen with the text 'Sound Effects from zapsplat.com'.
Link: https://www.zapsplat.com/license-type/standard-license/

**Comment by SKIMSTER0** [comment]
Disregard previous comment, not going to risk potential lawsuit. Sounds are going to be from freesound.org.
